GENERAL:
  task: train  # train, test
  manual_seed: 123
  model_dir: model/DKNet.py
  dataset_dir: data/scannetv2_inst.py

  distributed: True

DATA:
  data_root: /mnt/lustre/share/jkyang/psg4d/hoi4d_3d
  dataset: hoi4d
  train_list_file: /mnt/lustre/share/jkyang/psg4d/dataset_jcenaa/dataset/hoi4d/list_train.txt
  test_list_file: /mnt/lustre/share/jkyang/psg4d/dataset_jcenaa/dataset/hoi4d/list_test.txt
  sampler_test: 300
  filename_suffix: _inst_nostuff.pth

  classes: 49
  ignore_label: -100
  invalid_classes: -1

  input_channel: 3
  scale: 50   # voxel_size = 1 / scale, scale 50(2cm)
  score_fullscale: 14
  score_mode: 4 # mean
  batch_size: 8
  test_batch_size: 1
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4 # 4=mean

STRUCTURE:
  model_name: DKNet
  d: 32 # 16 or 32
  block_residual: True
  block_reps: 2
  DyWeight: DFN

  use_coords: True
  add_transformer: False
  
TRAIN:
  epochs: 100
  train_workers: 8 # data loader workers
  optim: AdamW # Adam or SGD or AdamW
  lr: 0.001
  step_epoch: 50
  start_epoch: 0
  multiplier: 0.5
  momentum: 0.9
  weight_decay: 0.0001
  save_freq: 8  # also eval_freq
  test_epoch: True
  loss_weight: [1.0, 1.0, 1.0, 1.0] # semantic_loss, offset_norm_loss, offset_dir_loss, score_loss
  MAX_INST_NUM: 80

  pretrain_path: 
  pretrain_module: []
  prefetch_superpoints: False
  fix_module: []
  semantic_epochs: 20
  prepare_epochs: 4

  train_thres: 0.0
  train_local_thres: 0.5

TEST:
  split: val
  test_epoch: 100
  test_workers: 8
  test_seed: 567

  test_thres: 0.0
  test_local_thres: 0.5
  
  TEST_SCORE_THRESH: 0.1
  TEST_NPOINT_THRESH: 100

  eval: True
  save_semantic: False
  save_pt_offsets: False
  save_instance: False
  save_candidate: False
  save_res: True